./createBook.sh 中唐文豪.txt
./createBook.sh 凱撒大帝.txt
./createBook.sh 列寧.txt
./createBook.sh 劉邦項羽.txt
./createBook.sh 努爾哈赤.txt
./createBook.sh 包拯.txt
./createBook.sh 南唐後主李煜.txt
./createBook.sh 南越王趙佗.txt
./createBook.sh 卡斯特羅與哲古華拉.txt
./createBook.sh 史太林.txt
./createBook.sh 司馬光王安石.txt
./createBook.sh 司馬懿.txt
./createBook.sh 吳三桂.txt
./createBook.sh 哥倫布與麥哲倫.txt
./createBook.sh 唐太宗.txt
./createBook.sh 喬治華盛頓.txt
./createBook.sh 威廉大帝.txt
./createBook.sh 孔子.txt
./createBook.sh 安祿山.txt
./createBook.sh 宋太祖、宋太宗.txt
./createBook.sh 宋徽宗.txt
./createBook.sh 岳飛.txt
./createBook.sh 岸信介.txt
./createBook.sh 希特拉.txt
./createBook.sh 彼德大帝.txt
./createBook.sh 德川家康.txt
./createBook.sh 成吉思汗.txt
./createBook.sh 戴卓爾夫人.txt
./createBook.sh 戴高樂.txt
./createBook.sh 拿破崙.txt
./createBook.sh 明崇禎帝.txt
./createBook.sh 明治天皇.txt
./createBook.sh 昭和天皇.txt
./createBook.sh 曹操.txt
./createBook.sh 曾國藩.txt
./createBook.sh 朗奴﹒列根.txt
./createBook.sh 朱元璋.txt
./createBook.sh 朴正熙.txt
./createBook.sh 林則徐.txt
./createBook.sh 林肯.txt
./createBook.sh 梁啟超.txt
./createBook.sh 梁武帝.txt
./createBook.sh 楊家將.txt
./createBook.sh 武則天.txt
./createBook.sh 洪秀全.txt
./createBook.sh 漢光武帝.txt
./createBook.sh 玄奘法師.txt
./createBook.sh 王冠與十字架_—_亨利八世到查理一世.txt
./createBook.sh 王莽.txt
./createBook.sh 甘地.txt
./createBook.sh 科爾.txt
./createBook.sh 秦始皇.txt
./createBook.sh 約翰．甘迺迪.txt
./createBook.sh 維多利亞女王.txt
./createBook.sh 胡志明.txt
./createBook.sh 胡適.txt
./createBook.sh 興宣大院君.txt
./createBook.sh 莫臥兒帝國群英錄.txt
./createBook.sh 萬曆帝.txt
./createBook.sh 蔡元培.txt
./createBook.sh 蔣宋美齡與蔣家婦女.txt
./createBook.sh 蘇軾.txt
./createBook.sh 袁世凱.txt
./createBook.sh 諸葛亮.txt
./createBook.sh 豐臣秀吉.txt
./createBook.sh 赫魯曉夫.txt
./createBook.sh 達文西.txt
./createBook.sh 邱吉爾.txt
./createBook.sh 鄭和.txt
./createBook.sh 鄭成功.txt
./createBook.sh 阿拉伯的勞倫斯.txt
./createBook.sh 隋文帝隋煬帝.txt
./createBook.sh 雍正皇帝.txt
./createBook.sh 馬可波羅.txt
./createBook.sh 魯迅.txt
