python3 rthk_qplaylist.py "31看世界 - K-Pop 夢工場"
python3 rthk_qplaylist.py "31看世界 - 鬥快去印尼"
python3 rthk_qplaylist.py "31看世界 - 超時空尋找"
python3 rthk_qplaylist.py "31看世界 - Gordon Ramsay 瘋味之旅 4"
python3 rthk_qplaylist.py "31看世界 - 史前系列：冰河時期 - 冰封世界"
python3 rthk_qplaylist.py "31看世界 - 珍古德的足跡"
python3 rthk_qplaylist.py "31看世界 - 科技保育"
python3 rthk_qplaylist.py "31看世界 - 航拍海岸線 (第一季)"
python3 rthk_qplaylist.py "31看世界 - 深夜潛行"
python3 rthk_qplaylist.py "31看世界 - 超級食物：豆"
python3 rthk_qplaylist.py "31看世界 – 地震偵探"
python3 rthk_qplaylist.py "31看世界 – 運動科學之極限解碼"
python3 rthk_qplaylist.py "31看世界 – 維克托的極限清單2"
python3 rthk_qplaylist.py "31看世界 – 巔峰工程"
