python3 rthk_playlist.py "31看世界 - K-Pop 夢工場"
python3 rthk_playlist.py "31看世界 - 鬥快去印尼"
python3 rthk_playlist.py "31看世界 - 超時空尋找"
python3 rthk_playlist.py "31看世界 - Gordon Ramsay 瘋味之旅 4"
python3 rthk_playlist.py "31看世界 - 千年陝菜 (第二季)"
python3 rthk_playlist.py "31看世界 - 大腦解碼"
python3 rthk_playlist.py "31看世界 - 大熊貓雲川和鑫寶"
python3 rthk_playlist.py "31看世界 - 史前系列：冰河時期 - 冰封世界"
python3 rthk_playlist.py "31看世界 - 本草流芳"
python3 rthk_playlist.py "31看世界 - 舌尖上的中國 (第四季)"
python3 rthk_playlist.py "31看世界 - 因為遇見你"
python3 rthk_playlist.py "31看世界 - 向新出發"
python3 rthk_playlist.py "31看世界 - 但是還有書籍 (第一季)"
python3 rthk_playlist.py "31看世界 - 但是還有書籍 (第二季)"
python3 rthk_playlist.py "31看世界 - 泥的名字"
python3 rthk_playlist.py "31看世界 - 珍古德的足跡"
python3 rthk_playlist.py "31看世界 - 科技保育"
python3 rthk_playlist.py "31看世界 - 穿越蘑菇雲的人"
python3 rthk_playlist.py "31看世界 - 航拍海岸線 (第一季)"
python3 rthk_playlist.py "31看世界 - 深夜潛行"
python3 rthk_playlist.py "31看世界 - 淨零排放新時代"
python3 rthk_playlist.py "31看世界 - 尋色中國"
python3 rthk_playlist.py "31看世界 - 超級食物：豆"
python3 rthk_playlist.py "31看世界 - 鄔達克"
python3 rthk_playlist.py "31看世界 - 認知障礙知多少"
python3 rthk_playlist.py "31看世界 - 魅力阿聯酋"
python3 rthk_playlist.py "31看世界 - 養貓的人"
python3 rthk_playlist.py "31看世界 – 大自然奧秘"
python3 rthk_playlist.py "31看世界 – 白牛"大使""
python3 rthk_playlist.py "31看世界 – 地震偵探"
python3 rthk_playlist.py "31看世界 – 我所看見的風暴"
python3 rthk_playlist.py "31看世界 – 我所看見的颶風"
python3 rthk_playlist.py "31看世界 – 運動科學之極限解碼"
python3 rthk_playlist.py "31看世界 – 維克托的極限清單2"
python3 rthk_playlist.py "31看世界 – 巔峰工程"
